apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: abn-dmp-poi-map-app-dev
  annotations:
    argocd/app-name: abn-dmp-poi-map-app-dev
    backstage.io/kubernetes-id: abn-dmp-poi-map-app
    backstage.io/kubernetes-namespace: abn-dmp
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-aro24/abn-dmp-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/dev-pipelines/ns/abn-dmp/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/k8s/ns/abn-dmp/deployments/abn-dmp-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.kovj5vhc.eastus.aroapp.io/#https://github.com/rhdh-aro24/abn-dmp-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://abn-dmp-poi-map-app-abn-dmp.apps.kovj5vhc.eastus.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:abn-dmp"
  system: workshop-system-abn-dmp
  consumesApis:
    - gateway-api-abn-dmp
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-abn-dmp
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:abn-dmp"
